baseURL: https://donchan922.com
title: donchan922.com
theme: "PaperMod"

frontmatter:
  lastmod:
  - :fileModTime

defaultContentLanguage: "ja"
enableRobotsTXT: true
buildDrafts: false
buildFuture: false
buildExpired: false

minify:
  disableXML: true
  minifyOutput: true

publishDir: "docs"

params:
  env: production
  profileMode:
    enabled: true
    title: "Daiki Tsukuda"
    imageUrl: "/images/icon.png"
    imageTitle: icon
    buttons:
      - name: About
        url: "/about"
      - name: Works
        url: "/works"
      - name: Contact
        url: "/contact"
  hidemeta: true
  disableScrollToTop: true
