baseURL: https://donchan922.com
title: donchan922.com
theme: "PaperMod"

frontmatter:
  lastmod:
    - :fileModTime

defaultContentLanguage: "ja"
enableRobotsTXT: true
buildDrafts: false
buildFuture: false
buildExpired: false

minify:
  disableXML: true
  minifyOutput: true

publishDir: "docs"

params:
  env: production
  description: "👋 Welcome to donchan922.com"
  profileMode:
    enabled: true
    imageUrl: "/images/icon.png"
    imageTitle: icon
  hidemeta: true
  disableScrollToTop: true
