name: md-to-pdf

on: push

jobs:
  convert_via_pandoc:
    runs-on: ubuntu-18.04
    steps:
      - run: ls /github/workspace/README.md
      - uses: docker://pandoc/core:2.9
        with:
          args: >-
            --output=README.pdf
            /github/workspace/README.md

